export const imageMapper = {
  folder: "directory_folder.png",
  small_folder_up: "directory_up_small.png",
  small_folder_back: "directory_back_small.png",
  documents: "directory_docs.png",
  bookmarks: "directory_bookmarks.png",
  text: "text_file.png",
  note: "note.png",
  drive: "hard_drive.png",
  executable: "executable.png",
  dos: "dos.png",
  internet: "internet_explorer.png",
  tetris: "program_icons/tetris3-48.png",
  minesweeper: "program_icons/mine-48.png",
  hover: "program_icons/hover2-48.png",
  video: "program_icons/video-48.png",
  chat: "program_icons/aim2-48.png",
  notepad: "note.png",
  taskmanager: "program_icons/taskManager-48.png",
  programs: "programs.png",
  README: "README.png",
}
