export const programs = [
  {
    name: "Tetris",
    image_url: "./assets/program_icons/tetris3-48.png",
    icon_url: "./assets/program_icons/tetris3-48.png",
    width: 600,
    height: 600,
  },
  {
    name: "Terminal",
    image_url: "./assets/program_icons/terminal2-48.png",
    icon_url: "./assets/program_icons/terminal2-48.png",
    width: 200,
    height: 200,
  },
  {
    name: "Hover",
    image_url: "./assets/program_icons/hover2-48.png",
    icon_url: "./assets/program_icons/hover2-48.png",
    width: 600,
    height: 600,
  },
  {
    name: "Video Player",
    image_url: "./assets/program_icons/video-48.png",
    icon_url: "./assets/program_icons/video-48.png",
    width: 600,
    height: 600,
  },
  {
    name: "My Computer",
    image_url: "/assets/program_icons/computer_explorer.png",
    icon_url: "./assets/program_icons/computer_explorer.png",
    width: 600,
    height: 400,
  },
  {
    name: "Notepad",
    image_url: "/assets/note.png",
    icon_url: "/assets/note.png",
    width: 400,
    height: 400,
  },
  {
    name: "Minesweeper",
    image_url: "/assets/program_icons/mine-48.png",
    icon_url: "/assets/program_icons/mine-48.png",
    width: 373,
    height: 456,
  },
  {
    name: "Chat App",
    image_url: "/assets/program_icons/aim2-48.png",
    icon_url: "/assets/program_icons/aim2-48.png",
    width: 600,
    height: 400,
  },
]
