export const programs = [
  {
    name: "Tetris",
    image_url: "./assets/program_icons/tetris2.png",
    icon_url: "./assets/program_icons/tetris.png",
    width: 600,
    height: 600,
  },
  {
    name: "Terminal",
    image_url: "./assets/program_icons/terminal2.png",
    icon_url: "./assets/program_icons/terminal.png",
    width: 200,
    height: 200,
  },
  {
    name: "Hover",
    image_url: "./assets/program_icons/hover2.png",
    icon_url: "./assets/program_icons/hover2.png",
    width: 600,
    height: 600,
  },
  {
    name: "Video Player",
    image_url: "./assets/program_icons/video.png",
    icon_url: "./assets/program_icons/video.png",
    width: 600,
    height: 600,
  },
  {
    name: "My Computer",
    image_url: "/assets/program_icons/computer_explorer.png",
    icon_url: "./assets/program_icons/computer_explorer.png",
    width: 600,
    height: 400,
  },
  {
    name: "Notepad",
    image_url: "/assets/note.png",
    icon_url: "/assets/note.png",
    width: 400,
    height: 400,
  },
  {
    name: "Minesweeper",
    image_url: "/assets/program_icons/mine.png",
    icon_url: "/assets/program_icons/mine.png",
    width: 600,
    height: 680,
  },
  {
    name: "Chat App",
    image_url: "/assets/program_icons/aim2.png",
    icon_url: "/assets/program_icons/aim2.png",
    width: 600,
    height: 400,
  },
  // {
  //   name: "Test",
  //   image_url: "/assets/program_icons/aim2.png",
  //   icon_url: "/assets/program_icons/aim2.png",
  //   width: 600,
  //   height: 400,
  // },
]
